const inquirer = require('inquirer');
const util = require('util');
const exec = util.promisify(require('child_process').exec);

const copyFromGit = async (service, project, cwd, folder) => {
  console.log(cwd);
  await exec(`svn export https://github.com/shopkeepjs/shopkeepjs/trunk/store/${service}/${project} ${cwd}/${folder}`, {
    cwd,
  });
};

const createGitRepo = async (projectName, isNewDirectory) => {
  const { githubUserName } = await inquirer.prompt([
    {
      type: 'text',
      name: 'githubUserName',
      prefix: '',
      message: 'What is your github user name?'.green.italic,
      transformer: (answer) => `${answer}`.blue,
    },
  ]);
  try {
    await exec(`hub create ${githubUserName}/${projectName}`, { cwd: isNewDirectory ? `${projectName}` : '' });
  } catch (error) {
    console.error('It appears you have encountered an error: ', error);
  }
};

const makeGitProject = async (projectName, isNewDirectory) => {
  const { shouldCreateNewGit } = await inquirer.prompt([
    {
      type: 'confirm',
      name: 'shouldCreateNewGit',
      message: '\n Would you like to create a git repo and push immediately?'.green.italic,
      prefix: '   - Warning: this requires hub - '.yellow.bold,
      default: false,
    },
  ]);
  if (shouldCreateNewGit) {
    await createGitRepo(projectName, isNewDirectory);
    await exec('git push origin master', { cwd: isNewDirectory ? `${projectName}` : '' });
  }
};

const git = async ({ cwd }) => {
  await exec('git init', { cwd });
  await exec('git add .', { cwd });
  await exec("git commit -m 'Generated by ShopkeepJS'", { cwd });
};

module.exports = { git, copyFromGit };
