const inquirer = require('inquirer');
const util = require('util');
const exec = util.promisify(require('child_process').exec);
// const { detectGH } = require('./dependencyCheck');

const copyFromGit = async (service, project, cwd) => {
  await exec(`svn export https://github.com/shopkeepjs/shopkeepjs/trunk/store/${service}/${project} ${cwd}/${service}`);
};

// eslint-disable-next-line no-unused-vars
const createGitRepo = async (projectName, cwd) => {
  const { shouldCreateNewGit } = await inquirer.prompt([
    {
      type: 'confirm',
      name: 'shouldCreateNewGit',
      message: '\n Would you like to create a git repo and push immediately?'.green.italic,
      prefix: '   - GH is detected - '.yellow.bold,
      default: false,
    },
  ]);
  if (shouldCreateNewGit) {
    const gitUsername = await exec('gh auth status').then(({ stderr }) => {
      const test = stderr.slice(stderr.search('as ') + 3);
      return test.slice(0, test.search(' '));
    });
    const { githubAccount } = await inquirer.prompt([
      {
        type: 'text',
        name: 'githubAccount',
        prefix: '',
        message: 'Which github account or organization would you like to use?'.green.italic,
        default: gitUsername,
        transformer: (answer) => `${answer}`.blue,
      },
    ]);
    await exec(`gh repo create ${githubAccount}/${projectName} --public -y`, { cwd });
  }
};

const branchNaming = async () => {
  const { defaultBranch } = await inquirer.prompt([
    {
      type: 'text',
      name: 'defaultBranch',
      prefix: '',
      message: 'What would you like your default branch to be called?'.green.italic,
      default: 'main',
      transformer: (answer) => `${answer}`.blue,
    },
  ]);
  const { willAddDevBranch } = await inquirer.prompt([
    {
      type: 'confirm',
      name: 'willAddDevBranch',
      prefix: '',
      message: 'Would you like to create a dev branch?'.green.italic,
      default: true,
      transformer: (answer) => `${answer}`.blue,
    },
  ]);
  if (willAddDevBranch) {
    const { devBranch } = await inquirer.prompt([
      {
        type: 'text',
        name: 'devBranch',
        prefix: '',
        message: 'What would you like your dev branch to be called?'.green.italic,
        default: 'dev',
        transformer: (answer) => `${answer}`.blue,
      },
    ]);
    return { defaultBranch, devBranch };
  }
  return { defaultBranch };
};

const pushToGitHub = async ({ defaultBranch, devBranch, cwd }) => {
  await exec(`git push origin ${defaultBranch}`, { cwd });
  if (devBranch) {
    await exec(`git checkout -b ${devBranch}`, { cwd });
    await exec(`git push origin ${devBranch}`, { cwd });
  }
  const { stdout: currentBranch } = await exec('git branch --show-current', { cwd });
  if (currentBranch.trim() === `${defaultBranch}` && devBranch) await exec(`git checkout -b ${devBranch}`, { cwd });
};

// eslint-disable-next-line no-unused-vars
const git = async ({ projectName, cwd }) => {
  const { defaultBranch, devBranch } = await branchNaming();
  await exec(`git init -b ${defaultBranch}`, { cwd });
  await exec('git add .', { cwd });
  await exec("git commit -m 'Generated by ShopkeepJS'", { cwd });
  // if (await detectGH()) await createGitRepo(projectName, cwd, defaultBranch, devBranch);
  return { defaultBranch, devBranch };
};

module.exports = { git, copyFromGit, pushToGitHub };
