web:
  env_file:
    - docker-variables.env

services:
    app:
      image: {PROJECT_NAME}
      build: .
      restart: always
      ports:
        - 5000:${PORT}
      volumes:
        - {SERVER_FOLDER}:/usr/src/app:cached